#!/usr/bin/env python3
import sys
from server.main import server

try:
    # Get a passphrase from commandline argument
    if len(sys.argv) == 2:
        input_passphrase = str(sys.argv[1])
        server(input_passphrase)
    else:
        print ("Give me passphrase")
except KeyboardInterrupt:
    print ("Ctrl_C pressed ... Shutting Down")
