from utils import bankDB
d = bankDB()
print(d.store_user('test3', 'test', 'test', 'email', 'mobile', 1000))
print(d.get_every_user_info('test3'))
print(d.store_user_info_modification('test3',{'user_pw':'1234','account_num':12345123455432154321,'github_id':'test','email':'test@test.com','mobile':'01043434343'}))
print(d.get_every_user_info('test3'))
print(d.store_transaction('test1', 'test2', 1000, "hi1"))
print(d.get_balance('test1'))
print(d.get_balance('test2'))
print(d.store_transaction('test1', 'test2', 1000, "hi2"))
print(d.get_balance('test1'))
print(d.get_balance('test2'))
print(d.store_transaction('test1', 'test2', 1000, "hi3"))
print(d.get_balance('test1'))
print(d.get_balance('test2'))
print(d.remove_user_account('test3'))
print(d.get_every_user_info('test3'))
